### ISSUE TITLE
Info about compile/install

### ISSUE THREAD

**Issue by MasterCruelty** [johnstennett24/HaloMiniGame#1]
Hi, can you bring info about installation and running of the game?
Thank you

**Comment by johnstennett24** [comment]
Sure! Sorry I did not see that you had opened this. I will add the installation and running the game instructions in a README file.

**Comment by MasterCruelty** [comment]
> Sure! Sorry I did not see that you had opened this. I will add the installation and running the game instructions in a README file.

Don't worry! I'll wait :)

**Comment by johnstennett24** [comment]
Okay I added installation and running instructions. Let me know if you need anymore clarification, I am going to close this issue
